// AUTO-GENERATED by apps/mobile/scripts/sync-demo-media.mjs — do not edit by hand.
// Drop files into apps/mobile/assets/demo/ then re-run the script.
import type { ImageSourcePropType } from 'react-native';

export type DemoStoryMedia = {
  type: 'photo' | 'video';
  source: ImageSourcePropType;
  caption?: string;
};

export const PROFILE_PHOTOS: Partial<Record<string, ImageSourcePropType>> = {
  'me': require('../../assets/demo/profile-pics/brant.jpg'),
  'maya': require('../../assets/demo/profile-pics/jade.jpg'),
  'devon': require('../../assets/demo/profile-pics/kelton.jpg'),
  'ines': require('../../assets/demo/profile-pics/janna.jpg'),
  'kit': require('../../assets/demo/profile-pics/levi.jpg'),
  'theo': require('../../assets/demo/profile-pics/ben.jpg'),
  'nour': require('../../assets/demo/profile-pics/ceci.jpg'),
  'jordyn': require('../../assets/demo/profile-pics/jordyn.jpg'),
};

export const STORY_MEDIA: Partial<Record<string, DemoStoryMedia[]>> = {
  'me': [
    { type: 'photo', source: require('../../assets/demo/stories/brant/crazy.jpg') },
    { type: 'photo', source: require('../../assets/demo/stories/brant/england.jpg') },
    { type: 'video', source: require('../../assets/demo/stories/brant/neighbor.mov') }
  ],
  'maya': [
    { type: 'photo', source: require('../../assets/demo/stories/jade/bday.jpg') },
    { type: 'photo', source: require('../../assets/demo/stories/jade/wool.jpg') }
  ],
  'devon': [
    { type: 'photo', source: require('../../assets/demo/stories/kelton/hunt.jpg') },
    { type: 'photo', source: require('../../assets/demo/stories/kelton/kp.jpg') },
    { type: 'photo', source: require('../../assets/demo/stories/kelton/shoes.jpg') }
  ],
  'kit': [
    { type: 'photo', source: require('../../assets/demo/stories/levi/fancy.jpg') }
  ],
  'ines': [
    { type: 'photo', source: require('../../assets/demo/stories/janna/dinner.jpg') },
    { type: 'photo', source: require('../../assets/demo/stories/janna/roomies.jpg') }
  ]
};
